---
name: Text-Textile-Plaintext
version: 0.100
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
abstract: 'Convert Textile markup to plain-text, PS or RTF output'
license: perl
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Text-Textile-Plaintext
  homepage: http://search.cpan.org/dist/Text-Textile-Plaintext
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjray/text-textile-plaintext/tree/master
build_requires:
  Test::More: 0.80
requires:
  HTML::FormatText: 2.04
  HTML::TreeBuilder: 3.23
  Text::Textile: 2.12
  perl: 5.008
configure_requires:
  Module::Build: 0.340201
provides:
  App::Textile2x:
    file: lib/App/Textile2x.pm
    version: 0.100
  Text::Textile::Plaintext:
    file: lib/Text/Textile/Plaintext.pm
    version: 0.100
  Text::Textile::PostScript:
    file: lib/Text/Textile/PostScript.pm
    version: 0.100
  Text::Textile::RTF:
    file: lib/Text/Textile/RTF.pm
    version: 0.100
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
